server:
  port: 8081

spring:
  application:
    name: task-service

  profiles:
    default: local

  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis
    redis:
      time-to-live: 5m

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

services:
  notification:
    connect-timeout: ${NOTIFICATION_SERVICE_CONNECT_TIMEOUT:2s}
    read-timeout: ${NOTIFICATION_SERVICE_READ_TIMEOUT:3s}
    retry:
      max-attempts: ${NOTIFICATION_SERVICE_RETRY_MAX_ATTEMPTS:2}
      delay-millis: ${NOTIFICATION_SERVICE_RETRY_DELAY_MILLIS:500}
    circuit-breaker:
      failure-rate-threshold: ${NOTIFICATION_SERVICE_CIRCUIT_BREAKER_FAILURE_RATE_THRESHOLD:50}
      minimum-number-of-calls: ${NOTIFICATION_SERVICE_CIRCUIT_BREAKER_MINIMUM_NUMBER_OF_CALLS:4}
      sliding-window-size: ${NOTIFICATION_SERVICE_CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE:4}
      wait-duration-in-open-state: ${NOTIFICATION_SERVICE_CIRCUIT_BREAKER_WAIT_DURATION_IN_OPEN_STATE:10s}
      permitted-number-of-calls-in-half-open-state: ${NOTIFICATION_SERVICE_CIRCUIT_BREAKER_HALF_OPEN_CALLS:2}
    rate-limiter:
      limit-for-period: ${NOTIFICATION_SERVICE_RATE_LIMIT_FOR_PERIOD:3}
      limit-refresh-period: ${NOTIFICATION_SERVICE_RATE_LIMIT_REFRESH_PERIOD:10s}
      timeout-duration: ${NOTIFICATION_SERVICE_RATE_LIMIT_TIMEOUT_DURATION:0s}
